#!/bin/sh

TRAVIS_PGVERSION='9.1'
#if [ $PGVERSION != $TRAVIS_PGVERSION ]
#then
#  sudo -u postgres pg_dropcluster --stop $TRAVIS_PGVERSION main
  # Make psql use $PGVERSION
#  export PGCLUSTER=$PGVERSION/main
#fi

# Install postgres and solr
# We need this ppa so we can install postgres-8.4
#sudo add-apt-repository -yy ppa:pitti/postgresql
#sudo apt-get update -qq

# Don't require a password to access DB
sudo sed -i -e 's/ident/trust/g' /etc/postgresql/$PGVERSION/main/pg_hba.conf 

sudo service postgresql reload

pip install -r requirements-test.txt --use-mirrors

sudo -u postgres createdb -O writeuser datastore -E utf-8

psql -c 'CREATE USER writeuser;' -U postgres
psql -c 'CREATE USER readonlyuser;' -U postgres

sudo -u postgres psql -c "ALTER USER writeuser WITH PASSWORD 'pass';"

sudo -u postgres psql postgres -f set_permissions.sql

#python setup.py develop
#sed -i -e 's/.*datastore.write_url.*/ckan.datastore.write_url = postgresql:\/\/postgres@\/datastore/' development.ini

nosetests -v --nologcapture datastore/tests/

